name: cb_project
description: El proyecto de voto digital desarrollado en Flutter para el Ayuntamiento de Mexicali ofrece una solución completa y en tiempo real para realizar sesiones de votación. Con una aplicación de escritorio para administradores, una aplicación de TV y una aplicación para tablets, el sistema permite la gestión de usuarios, asignación de roles y la visualización actualizada de los puntos en la sesión, brindando una experiencia eficiente y transparente para facilitar la toma de decisiones.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  socket_io_client: ^2.0.0-beta.2
  loading_indicator: ^3.1.1
  json_annotation: ^4.8.1
  after_layout: ^1.2.0
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  fl_chart: ^0.63.0
  uuid: ^4.1.0
  excel: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/illustrations/
